import { useRef } from "react";
import "./Portfolio.scss";
import { motion, useScroll, useSpring, useTransform } from "framer-motion";

const items = [

    {
        id: 1,
        title: "Portfolio",
        img: "./logo1.png",
        desc: "Built using React for a smooth and seamless navigation experience",
        link:"https://github.com/mayank3213",
    },
    {
        id: 2,
        title: "Spelling Bee Game",
        img: "./logo2.png",
        desc: "Built an interactive game where users listen to a word and type its correct spelling, with instant feedback.",
        link:"https://github.com/mayank3213",
    },
    {
        id: 3,
        title: "Number Guessing Game",
        img: "./logo3.png",
        desc: "A number is randomly generated by the system each time the game is played.",
        link:"https://github.com/mayank3213",
    },
    {
        id: 4,
        title: "KeyBoard Music System",
        img: "./logo4.png",
        desc: "Specific keys on the keyboard are mapped to a specific beat or sound, allowing users to press keys to produce music.",
        link:"https://github.com/mayank3213",
    },

];

const Single = ({ item }) => {

    const ref = useRef();

    const { scrollYProgress } = useScroll({
        target: ref,
    });

    const y = useTransform(scrollYProgress, [0, 1], [-300,300]);

    return (

        <section>
            <div className="container">
                <div className="wrapper">
                    <div className="imageContainer" ref={ref}>
                        <img src={item.img} alt="" />
                    </div>

                    <motion.div className="textContainer" style={{y}} >
                        <h2> {item.title}</h2>
                        <p> {item.desc}</p>
                        <button><a href={item.link}>Github Link</a></button>
                    </motion.div>
                </div>
            </div>
        </section>
    );
};

const Portfolio = () => {

    const ref = useRef();

    const { scrollYProgress } = useScroll({
        target: ref,
        offset: ["end end", "start start"],
    });

    const scaleX = useSpring(scrollYProgress, {
        stiffness: 1000,
        damping: 30,
    });

    return (

        <div className="portfolio" ref={ref}>
            <div className="progress">
                <h1>PERSONAL PROJECTS</h1>
                <motion.div style={{ scaleX}} className="progressBar"></motion.div>
            </div>
            {items.map((item) => (
                <Single item={item} key={item.id} />
            ))}
        </div>
    );
};


export default Portfolio;